name: stand-secure-ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs: 
  ci:
    runs-on: ubuntu-slim
    steps: 
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Trivy scanner fs
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL'
          exit-code: '1'
      - name: Build image
        run: docker build -t stand-secure-ci:ci .
      - name: Trivy scanner image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'image'
          image-ref: 'stand-secure-ci:ci'
          severity: 'CRITICAL'
          exit-code: '1'

  